### PR TITLE
Add Pythia

### PR DESCRIPTION
**Pull request by DamienIrving**

### CODE REVIEW

**Comment by paigem** [comment]
The JupyterBook was not successfully built after merging this PR, and yields the following error: `ImportError: cannot import name 'environmentfilter' from 'jinja2'`. See log info [here](https://github.com/ACDguide/BigData/runs/6002902490?check_suite_focus=true).

A quick Google shows that this might be an [issue with the the version of `jinja2`](https://github.com/readthedocs/readthedocs.org/issues/9037#issuecomment-1077818554). I'll leave this to discuss at the meeting today.

**Comment by paigem** [comment]
Build error has been fixed! The link above provided the solution: pin an older version of `jinja2` in `requirements.txt`.
